import { ThemeConfig, ThemeId } from '../types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  default: {
    id: 'default',
    name: 'Claro Minimalista',
    description: 'Tema por defecto: Fondo claro, botones negros y letras blancas.',
    badge: 'Por Defecto',
    bgClass: 'bg-slate-50',
    surfaceClass: 'bg-white',
    buttonClass: 'bg-black text-white hover:bg-neutral-800',
    buttonHoverClass: 'hover:bg-neutral-800',
    buttonTextClass: 'text-white',
    accentTextClass: 'text-black',
    accentBgClass: 'bg-black',
    accentBorderClass: 'border-black',
    headerBgClass: 'bg-white border-slate-200',
    raw: {
      bg: '#f8fafc',
      primaryBtn: '#000000',
      primaryBtnText: '#ffffff',
      accent: '#000000',
      border: '#e2e8f0',
    },
  },
  rojo: {
    id: 'rojo',
    name: 'Rojo Pasión',
    description: 'Fondo suave rojizo con botones en tono rojo carmesí.',
    badge: 'Energético',
    bgClass: 'bg-red-50/60',
    surfaceClass: 'bg-white',
    buttonClass: 'bg-red-600 text-white hover:bg-red-700',
    buttonHoverClass: 'hover:bg-red-700',
    buttonTextClass: 'text-white',
    accentTextClass: 'text-red-600',
    accentBgClass: 'bg-red-600',
    accentBorderClass: 'border-red-600',
    headerBgClass: 'bg-white/95 border-red-100',
    raw: {
      bg: '#fef2f2',
      primaryBtn: '#dc2626',
      primaryBtnText: '#ffffff',
      accent: '#dc2626',
      border: '#fee2e2',
    },
  },
  cafe: {
    id: 'cafe',
    name: 'Café Espresso',
    description: 'Fondo tono crema/lino tostado con botones café profundo.',
    badge: 'Artesanal',
    bgClass: 'bg-[#faf6f0]',
    surfaceClass: 'bg-white',
    buttonClass: 'bg-[#452b1e] text-white hover:bg-[#321f15]',
    buttonHoverClass: 'hover:bg-[#321f15]',
    buttonTextClass: 'text-white',
    accentTextClass: 'text-[#452b1e]',
    accentBgClass: 'bg-[#452b1e]',
    accentBorderClass: 'border-[#452b1e]',
    headerBgClass: 'bg-white/95 border-[#ede3d5]',
    raw: {
      bg: '#faf6f0',
      primaryBtn: '#452b1e',
      primaryBtnText: '#ffffff',
      accent: '#452b1e',
      border: '#ede3d5',
    },
  },
  naranja: {
    id: 'naranja',
    name: 'Naranja Ámbar',
    description: 'Fondo tono cálido durazno con botones naranja vibrante.',
    badge: 'Cálido',
    bgClass: 'bg-orange-50/70',
    surfaceClass: 'bg-white',
    buttonClass: 'bg-orange-600 text-white hover:bg-orange-700',
    buttonHoverClass: 'hover:bg-orange-700',
    buttonTextClass: 'text-white',
    accentTextClass: 'text-orange-600',
    accentBgClass: 'bg-orange-600',
    accentBorderClass: 'border-orange-600',
    headerBgClass: 'bg-white/95 border-orange-100',
    raw: {
      bg: '#fff7ed',
      primaryBtn: '#ea580c',
      primaryBtnText: '#ffffff',
      accent: '#ea580c',
      border: '#ffedd5',
    },
  },
};

export function getTheme(id: ThemeId = 'default'): ThemeConfig {
  return THEMES[id] || THEMES.default;
}
